name: Enterprise DevOps CICD Pipeleine
on:
  push:
    branches:
       - qa
    paths:
       - client/**
       - server/**
       - .github/workflows/qa-cicd.yml
permissions: 
      contents: write
      id-token: write

jobs:
  gitleaks-scan:
      name: Gitleaks scan
      runs-on: ubuntu-latest
      steps:
         - name: checkout source code
           uses: actions/checkout@v4

         - name: Run Gitleaks scan
           run: |
             docker run --rm \
             -v "${{ github.workspace }}:/repo" \
             zricethezav/gitleaks:latest detect \
             --source=/repo \
             --report-format=json \
             --report-path=/repo/gitleaks-report.json \
             --redact \
             --exit-code 0

         - name: Upload Gitleaks report
           uses: actions/upload-artifact@v4
           with:
              name: gitleaks-report
              path: gitleaks-report.json
              if-no-files-found: warn


  checkov-terraform:
        name: Checkov Terraform scan
        runs-on: ubuntu-latest
        needs:  gitleaks-scan
        steps:
          - name: Checkout source code
            uses: actions/checkout@v4

          - name: Setup Python
            uses: actions/setup-python@v4
            with:
              python-version: "3.11"

          - name: Install Checkov
            run: pip install checkov
          - name: Run checkov Terraform scan
            run: |
              checkov -d .\
              --framework terraform \
              --output json > checkov-terraform-report.json || true

          - name: Upload checkov Terraform report
            uses: actions/upload-artifact@v4
            with:
              name: checkov-terraform-report
              path: checkov-terraform-report.json
              if-no-files-found: warn


  checkov-k8s:
        name: Checkov Kubernetes Scan
        runs-on: ubuntu-latest
        needs:  gitleaks-scan
        steps:
          - name: Checkout Source Code
            uses: actions/checkout@v4
          - name: Stepu Python
            uses: actions/setup-python@v5  
            with:
              python-version: "3.11"
          - name: Install Checkov
            run: pip install checkov
          - name: Run checkov Kubernetes scan
            run: |
             checkov -d . \
               --framework kubernetes \
               --output json > checkov-k8s-report.json || true
          - name: Upload Checkov Kubernetes Report
            uses: actions/upload-artifact@v4
            with:
              name: checkov-k8s-report
              path: chekov-k8s-rport.json
              if-no-files-found: warn

  checkov-dockerfile:
      name: Checkov Dockerfile Scan
      runs-on: ubuntu-latest
      needs: gitleaks-scan
      steps:
        - name: checkout source code
          uses: actions/checkout@v4
        - name: setup Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.11"
        - name: Install checkov
          run: pip install checkov
        - name: Run checkov Dockerfile scan
          run: |
            checkov -d . \
              --framework dockerfile \
              --output json > checkov-dockerfile-report.json || true
        - name: upload checkov Dockerfile report
          uses: actions/upload-artifact@v4
          with:
            name: checkov-dockerfile-report
            path: checkov-dockerfile-report.json
            if-no-files-found: warn

  client-trivy-fs:
    name: Client Trivy FS Scan
    runs-on: ubuntu-latest
    needs: gitleaks-scan


    steps: 
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.6
        with:
          version: latest
          cache: true

      - name: Verify Trivy Installation
        run: |
          trivy --version
          which trivy

      - name: Run Trivy FS scan on client(json)
        run: |
          trivy fs ./client \
          --format json \
          --output client-trivy-fs-report.json \
          --severity HIGH,CRITICAL \
          --ignore-unfixed \
          --exit-code 0


      - name: Run Trivy scan on client(Table)
        run: |
          trivy fs ./client \
          --format table \
          --severity HIGH,CRITICAL \
          --ignore-unfixed \
          --exit-code 0 > client-trivy-fs-report.txt

      - name: Upload client Trivy JSON report
        uses: actions/upload-artifact@v4
        with:
           name: client-trivy-fs-json-report
           path: client-trivy-fs-report.json
           if-no-files-found: warn

      - name: Upload client Trivy Table report
        uses: actions/upload-artifact@v4
        with:
           name: client-trivy-fs-table-report
           path: client-trivy-fs-report.txt
           if-no-files-found: warn

  
  server-trivy-fs:
    name: Server Trivy FS Scan
    runs-on: ubuntu-latest
    needs: gitleaks-scan

    steps:
      - name: checkout source code
        uses: actions/checkout@v4

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.6
        with:
           version: latest
           cache: true

      - name: Verify Trivy Installation
        run: |
          trivy --version
          which trivy


      - name: Run Trivy FS scan on server (JSON)
        run: |
          trivy fs ./server \
            --format json \
            --output server-trivy-fs-report.json \
            --severity HIGH,CRITICAL \
            --ignore-unfixed \
            --exit-code 0


      - name: Run Trivy FS scan on server(Table)
        run: |
           trivy fs ./server \
           --format table \
           --severity HIGH,CRITICAL \
           --ignore-unfixed \
           --exit-code 0 > server-trivy-fs-report.txt

      - name: Upload Server Trivy JSON report
        uses: actions/upload-artifact@v4
        with:
          name: server-trivy-fs-json-report
          path: server-trivy-fs-report.json
          if-no-files-found: warn

      - name: Upload server Trivy TABLE report
        uses: actions/upload-artifact@v4
        with:
           name: server-trivy-fs-table-report
           path: server-trivy-fs-report.txt
           if-no-files-found: warn






        





              
            

        
       
      










































































































































































































































             
